# Task 1: Safe Division Utility
print("--- Task 1: Safe Division Utility ---")
try:
    num = float(input("Enter numerator: "))
    den = float(input("Enter denominator: "))
    result = num / den
except ValueError:
    # Catching ValueError if the user enters text instead of numbers.
    # Recovery Strategy: Print a friendly error message and move on (no loop implemented here).
    print("Error: Please enter a valid number.")
except ZeroDivisionError:
    # Catching ZeroDivisionError to prevent a crash if the denominator is 0.
    # Recovery Strategy: Warn the user that division by zero is mathematically undefined.
    print("Error: Cannot divide by zero.")
else:
    print(f"Result: {result}")
finally:
    print("Operation Complete\n")


# Task 2: Bill Calculator with Error Handling
print("--- Task 2: Bill Calculator ---")
prices = [120, 350, 'abc', 500, -200, 800]
total = 0

for price in prices:
    try:
        # In Python, comparing a string ('abc') with an int (0) naturally raises a TypeError.
        # This is a more organic, "Pythonic" way to catch type issues than checking isinstance().
        if price < 0:
            raise ValueError("Negative price not allowed")
        total += price
    except TypeError:
        # Catching TypeError triggered by the < comparison or the += addition with a string.
        # Recovery Strategy: Skip the invalid item, notify the user, and continue the loop.
        print(f"Skipping invalid item '{price}': Not a number.")
    except ValueError as e:
        # Catching the custom ValueError we explicitly raised for negative numbers.
        # Recovery Strategy: Skip the negative item, print the custom message, and continue.
        print(f"Skipping invalid item '{price}': {e}")

print(f"Running Total: {total}\n")


# Task 3: Custom Exception: Age Validator
print("--- Task 3: Age Validator ---")
def check_age(age):
    if age < 1 or age > 120:
        raise ValueError("Age must be between 1 and 120")
    return age

try:
    user_age = int(input("Enter your age: "))
    valid_age = check_age(user_age)
    print(f"Age {valid_age} is valid.")
except ValueError as e:
    # Catching ValueError for both non-integer inputs and out-of-range ages.
    # Recovery Strategy: Print the specific error message generated by the exception.
    print(f"Error: {e}")
print()


# Task 4: File Reader with Exception Handling
print("--- Task 4: File Reader ---")
filename = input("Enter the filename to read: ")
try:
    # Using the context manager (with statement) automatically handles closing the file, 
    # even if an error occurs while reading it.
    with open(filename, 'r') as file:
        for _ in range(3):
            line = file.readline()
            if line:
                print(line.strip())
except FileNotFoundError:
    # Catching FileNotFoundError if the user typos the name or the file is missing.
    # Recovery Strategy: Inform the user the file doesn't exist.
    print("Error: The file does not exist.")
except PermissionError:
    # Catching PermissionError if the script lacks OS read rights for the file.
    # Recovery Strategy: Inform the user about the permissions issue.
    print("Error: You do not have permission to read this file.")
finally:
    print("File operation attempted.\n")


# Task 5: Mini Program: Safe Shopping Cart
print("--- Task 5: Safe Shopping Cart ---")
cart = []
while True:
    user_input = input("Enter price (or 'q' to quit): ").lower()
    
    if user_input == 'q':
        break
        
    # Block 1: Handle input type conversion
    try:
        price = float(user_input)
    except ValueError:
        # Catching ValueError if float() fails on non-numeric strings.
        # Recovery Strategy: Print error, use 'continue' to skip to the next loop iteration.
        print("Invalid input. Please enter a numeric price.")
        continue
        
    # Block 2: Handle business logic (negative values)
    try:
        if price < 0:
            raise ValueError("Price cannot be negative")
        cart.append(price)
    except ValueError as e:
        # Catching the specific ValueError we raised for negative numbers.
        # Recovery Strategy: Print the error message, do not append to cart, continue loop.
        print(f"Error: {e}")

print(f"Total items: {len(cart)}")
print(f"Total bill: {sum(cart)}")